### ISSUE TITLE
Leaderboard for Scaling NOW!!!

### ISSUE THREAD

**Issue by geleeroyale** [geleeroyale/donation-leaderboard#25]
# Put the first leaderboard into production!

To implement the final site further steps are needed once **frontend and backend are finished**.

**Attention:** Implementation should be done purely on the ```scalingnow``` branch.

- [x] change from rinkeby-testnet to ethereum-mainnet
- [x] change donation address to ScalingNOW multisig
```0x9cb8921aa376219950ba134c15d8f5ee2769c599```
- [x] add ScalingNOW!!! event announcement content
- [x] write instructions for leaderboard
- [x] Deploy and announce ScalingNOW donation leaderboard

**Comment by geleeroyale** [comment]
Update - We probably won't lock the branch at all. Removed the issue.
